language: cpp

addons:
  apt:
    packages:
      - cmake
      - cmake-data

compiler:
  - clang
  - gcc

env:
  - CONFIG="-DSEED=ZERO -DBENCH=0" TEST=""
  - CONFIG="-DSEED=ZERO -DBENCH=0 -DFP_PRIME=255 -DEC_METHD='PRIME' -DEP_METHD='PROJC;LWNAF;LWNAF;BASIC'" TEST="-E test_bn|test_fb|test_fpx|test_eb"
  - CONFIG="-DFP_PRIME=255 -DEC_METHD=EDWARD -DED_METHD='PROJC;LWNAF;LWNAF;BASIC'" TEST="-E test_bn|test_fb|test_fpx|test_eb"
  - CONFIG="-DFP_PRIME=255 -DEC_METHD=EDWARD -DED_METHD='EXTND;LWNAF_MIXED;LWNAF_MIXED;BASIC'" TEST="-E test_bn|test_fb|test_fpx|test_eb|test_ec"

script:
  - mkdir build && cd build
  - cmake $CONFIG  .. && make -j && ctest -E $TEST
  - cd .. && rm -rf build
