name: Build RELIC

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows Latest - MSVC",
              artifact: "windows-msvc.tar.xz",
              os: windows-latest,
              cc: "cl",
              cxx: "cl",
            }
          - {
              name: "Windows Latest - MinGW", artifact: "windows-mingw.tar.xz",
              os: windows-latest,
              cc: "gcc", cxx: "g++"
            }
          - {
              name: "Ubuntu Latest - GCC",
              artifact: "linux-gcc.tar.xz",
              os: ubuntu-latest,
              cc: "gcc-9",
              cxx: "g++-9",
            }
          - {
              name: "Ubuntu Latest - Clang",
              artifact: "linux-clang.tar.xz",
              os: ubuntu-latest,
              cc: "clang-9",
              cxx: "clang++-9",
            }

    steps:
      - uses: actions/checkout@v2

      - name: Set Windows ENV
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: sudo apt install libgmp-dev

      - name: CMake Configure
        run: cmake -Bbuild -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DSEED= -DBENCH=0

      - name: CMake Build
        run: cmake --build build

      - name: CMake Test
        run: ctest .
