name: Build RELIC

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows Latest - MSVC",
              artifact: "windows-msvc.tar.xz",
              os: windows-latest,
              cc: "cl",
            }
          - {
              name: "Windows Latest - MinGW",
              artifact: "windows-mingw.tar.xz",
              os: windows-latest,
              cc: "gcc"
            }
          - {
              name: "Ubuntu Latest - GCC",
              artifact: "linux-gcc.tar.xz",
              os: ubuntu-latest,
              cc: "gcc",
            }
          - {
              name: "Ubuntu Latest - Clang",
              artifact: "linux-clang.tar.xz",
              os: ubuntu-latest,
              cc: "clang",
            }
          - {
              name: "MacOS Latest",
              os: macos-latest,
              cc: "clang",
            }
    steps:
      - uses: actions/checkout@v2

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: sudo apt install libgmp-dev

      - name: Set Windows enviroment
        if: runner.os == 'Windows' && matrix.cc == 'cl'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Run CMake
        shell: bash
        run: |
            mkdir build
            cd build
            echo ${MATRIX_CC}
            echo ${RUNNER_OS}
            if [ "${RUNNER_OS}" == "Windows" ] && [ "${CC}" == "gcc" ]; then
                cmake -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DSEED= -DBENCH=0 -G "MinGW Makefiles" ..
            else
                cmake -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DSEED= -DBENCH=0 ..
            fi
        env:
            CC: ${{ matrix.cc }}

      - name: CMake Build
        run: cmake --build build

      - name: CMake Test
        run: |
            cd build
            ctest .
