name: Basic configuration (Win64)

on:
  push:
    branches:
      - win64

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows Latest - MSVC",
            artifact: "windows-msvc.tar.xz",
            os: windows-latest,
            cc: "cl",
          }
    steps:
      - uses: actions/checkout@v2

      - name: Set Windows enviroment
        if: ${{ (runner.os == 'Windows') && (matrix.config.cc == 'cl') }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: Run CMake (Win)
        if: ${{ (runner.os == 'Windows') && (matrix.config.cc == 'cl') }}
        shell: bash
        run: |
          mkdir build
          cd build
          cmake -DSEED= -DBENCH=0 -G "NMake Makefiles" ..

      - name: CMake Build
        run: cmake --build build

      - name: CMake Test
        run: |
          cd build
          ctest --verbose .
